Canonical isomorph and automorphism group
AlgebraicJulia/ACSets.jl pull request #43
Opened 2023-07-06 23:12 UTC by kris-brown

This PR incorporates the interface with `nauty.c` from CSetAutomorphisms.jl. Rather than relying on a path to the `dreadnaut` executable (a high-level text-based interface for `nauty`), we use the path provided by nauty_jll. 

Nauty operates on undirected graphs, so a big portion of the code involves encoding/decoding ACSets as undirected graphs. The result of applying Nauty to an ACSet is a `CanonicalCSet`, which is currently the only subtype of the abstract type `NautyRes` (in general, we will want canonical forms of diagrams of ACSets, etc.). For any `NautyRes` there is an associated hash, orbit information, canonical isomorph, an iso from the input into that canonical isomorph, and a set of generators of the automorphism group. There is also code here which computes the full automorphism group given the generators.

Because ACSetTransformations belong in Catlab rather than ACSets.jl, the notion of a map between ACSets is a `Dict{Symbol, Vector{Int}}`.

A future improvement is to extend this to work with VarACSets.

2023-07-11 03:12 UTC, kris-brown commented
Seems like Windows is [not a supported platform](https://github.com/JuliaPackaging/Yggdrasil/blob/master/N/nauty/build_tarballs.jl#L51) for `nauty_jll` after all, so I skip those tests for Windows.

2023-10-05 20:26 UTC, kris-brown commented
This feature was implicitly requested by Paul Dancstep who was interested in a project related to enumerating slices of graphs up to isomorphism.

2023-10-10 00:12 UTC, KevinArlin requested changes

2023-10-10 15:24 UTC, kris-brown commented on src/NautyInterface.jl
> +  cd = deepcopy(X)
hm may that could be an Issue? I guess that would be something of the right shape but all the homs and attrs are undefined?

2023-10-10 15:32 UTC, kris-brown commented on src/NautyInterface.jl
> +    f = collect(X[h])
yeah the issue is that the raw nauty result seems to specify an iso in the other direction, whereas I think the natural thing (viewing the canonical morphism as something which takes you *to* a normal form) is to have the inverse. 

A solution could be to `inv` the the thing right upon parsing it from nauty output and then `inv` everything here.

2023-10-10 15:45 UTC, kris-brown commented on src/NautyInterface.jl
> +
Hm would that only help performance if we were to do actual linear algebra with it? My understanding is that the matrix only exists to be converted into a string for `dreadnaut` input.

2023-10-10 15:50 UTC, kris-brown commented on src/NautyInterface.jl
> +
haha I don't think so! But `prime` seemed appropriate for "rename to be slightly different in a way that probably doesn't clash with any other name". But this makes me now think that things will break if someone actually has a hom `src` and a hom `_src`, so if it sounds good I can replace with:

`prime(hom_name::Symbol) = Symbol("$(hom_name)_$(hash(hom_name))")`

(I'd use `gensym` but this needs to be deterministic)

2023-10-10 15:53 UTC, kris-brown commented on src/NautyInterface.jl
> +"""
deleted the whole `struct`

2023-10-10 16:04 UTC, kris-brown commented on src/NautyInterface.jl
> +"""
made the docstring more complete!

2023-10-10 20:29 UTC, KevinArlin commented on src/NautyInterface.jl
> +
Well you only allocate ~half the space to a symmetric, right? But this is probably nitpicking.

2023-10-10 20:31 UTC, KevinArlin commented on src/NautyInterface.jl
> +"""
Sounds good to me.

2023-10-10 20:31 UTC, KevinArlin commented on src/NautyInterface.jl
> +  cd = deepcopy(X)
Yeah, that's how it works for Julia arrays and suchlike. I'll post an issue.

2023-10-10 20:32 UTC, KevinArlin commented on src/NautyInterface.jl
> +    f = collect(X[h])
I guess I don't mind as long as this is all getting fleshed out internally.

2023-10-10 20:32 UTC, KevinArlin commented on src/NautyInterface.jl
> +"""
Yep, sounds good.

2023-10-10 20:33 UTC, KevinArlin approved these changes

2023-10-10 22:29 UTC, merged